// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"
)

type Querier struct {
	DeleteVersionStub        func(context.Context, int64) error
	deleteVersionMutex       sync.RWMutex
	deleteVersionArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	deleteVersionReturns struct {
		result1 error
	}
	deleteVersionReturnsOnCall map[int]struct {
		result1 error
	}
	EnsureTableStub        func(context.Context) error
	ensureTableMutex       sync.RWMutex
	ensureTableArgsForCall []struct {
		arg1 context.Context
	}
	ensureTableReturns struct {
		result1 error
	}
	ensureTableReturnsOnCall map[int]struct {
		result1 error
	}
	InsertVersionStub        func(context.Context, int64) error
	insertVersionMutex       sync.RWMutex
	insertVersionArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	insertVersionReturns struct {
		result1 error
	}
	insertVersionReturnsOnCall map[int]struct {
		result1 error
	}
	LatestVersionStub        func(context.Context) (int64, error)
	latestVersionMutex       sync.RWMutex
	latestVersionArgsForCall []struct {
		arg1 context.Context
	}
	latestVersionReturns struct {
		result1 int64
		result2 error
	}
	latestVersionReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	ListAppliedStub        func(context.Context) ([]int64, error)
	listAppliedMutex       sync.RWMutex
	listAppliedArgsForCall []struct {
		arg1 context.Context
	}
	listAppliedReturns struct {
		result1 []int64
		result2 error
	}
	listAppliedReturnsOnCall map[int]struct {
		result1 []int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Querier) DeleteVersion(arg1 context.Context, arg2 int64) error {
	fake.deleteVersionMutex.Lock()
	ret, specificReturn := fake.deleteVersionReturnsOnCall[len(fake.deleteVersionArgsForCall)]
	fake.deleteVersionArgsForCall = append(fake.deleteVersionArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.DeleteVersionStub
	fakeReturns := fake.deleteVersionReturns
	fake.recordInvocation("DeleteVersion", []interface{}{arg1, arg2})
	fake.deleteVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Querier) DeleteVersionCallCount() int {
	fake.deleteVersionMutex.RLock()
	defer fake.deleteVersionMutex.RUnlock()
	return len(fake.deleteVersionArgsForCall)
}

func (fake *Querier) DeleteVersionCalls(stub func(context.Context, int64) error) {
	fake.deleteVersionMutex.Lock()
	defer fake.deleteVersionMutex.Unlock()
	fake.DeleteVersionStub = stub
}

func (fake *Querier) DeleteVersionArgsForCall(i int) (context.Context, int64) {
	fake.deleteVersionMutex.RLock()
	defer fake.deleteVersionMutex.RUnlock()
	argsForCall := fake.deleteVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Querier) DeleteVersionReturns(result1 error) {
	fake.deleteVersionMutex.Lock()
	defer fake.deleteVersionMutex.Unlock()
	fake.DeleteVersionStub = nil
	fake.deleteVersionReturns = struct {
		result1 error
	}{result1}
}

func (fake *Querier) DeleteVersionReturnsOnCall(i int, result1 error) {
	fake.deleteVersionMutex.Lock()
	defer fake.deleteVersionMutex.Unlock()
	fake.DeleteVersionStub = nil
	if fake.deleteVersionReturnsOnCall == nil {
		fake.deleteVersionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVersionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Querier) EnsureTable(arg1 context.Context) error {
	fake.ensureTableMutex.Lock()
	ret, specificReturn := fake.ensureTableReturnsOnCall[len(fake.ensureTableArgsForCall)]
	fake.ensureTableArgsForCall = append(fake.ensureTableArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.EnsureTableStub
	fakeReturns := fake.ensureTableReturns
	fake.recordInvocation("EnsureTable", []interface{}{arg1})
	fake.ensureTableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Querier) EnsureTableCallCount() int {
	fake.ensureTableMutex.RLock()
	defer fake.ensureTableMutex.RUnlock()
	return len(fake.ensureTableArgsForCall)
}

func (fake *Querier) EnsureTableCalls(stub func(context.Context) error) {
	fake.ensureTableMutex.Lock()
	defer fake.ensureTableMutex.Unlock()
	fake.EnsureTableStub = stub
}

func (fake *Querier) EnsureTableArgsForCall(i int) context.Context {
	fake.ensureTableMutex.RLock()
	defer fake.ensureTableMutex.RUnlock()
	argsForCall := fake.ensureTableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Querier) EnsureTableReturns(result1 error) {
	fake.ensureTableMutex.Lock()
	defer fake.ensureTableMutex.Unlock()
	fake.EnsureTableStub = nil
	fake.ensureTableReturns = struct {
		result1 error
	}{result1}
}

func (fake *Querier) EnsureTableReturnsOnCall(i int, result1 error) {
	fake.ensureTableMutex.Lock()
	defer fake.ensureTableMutex.Unlock()
	fake.EnsureTableStub = nil
	if fake.ensureTableReturnsOnCall == nil {
		fake.ensureTableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureTableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Querier) InsertVersion(arg1 context.Context, arg2 int64) error {
	fake.insertVersionMutex.Lock()
	ret, specificReturn := fake.insertVersionReturnsOnCall[len(fake.insertVersionArgsForCall)]
	fake.insertVersionArgsForCall = append(fake.insertVersionArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.InsertVersionStub
	fakeReturns := fake.insertVersionReturns
	fake.recordInvocation("InsertVersion", []interface{}{arg1, arg2})
	fake.insertVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Querier) InsertVersionCallCount() int {
	fake.insertVersionMutex.RLock()
	defer fake.insertVersionMutex.RUnlock()
	return len(fake.insertVersionArgsForCall)
}

func (fake *Querier) InsertVersionCalls(stub func(context.Context, int64) error) {
	fake.insertVersionMutex.Lock()
	defer fake.insertVersionMutex.Unlock()
	fake.InsertVersionStub = stub
}

func (fake *Querier) InsertVersionArgsForCall(i int) (context.Context, int64) {
	fake.insertVersionMutex.RLock()
	defer fake.insertVersionMutex.RUnlock()
	argsForCall := fake.insertVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Querier) InsertVersionReturns(result1 error) {
	fake.insertVersionMutex.Lock()
	defer fake.insertVersionMutex.Unlock()
	fake.InsertVersionStub = nil
	fake.insertVersionReturns = struct {
		result1 error
	}{result1}
}

func (fake *Querier) InsertVersionReturnsOnCall(i int, result1 error) {
	fake.insertVersionMutex.Lock()
	defer fake.insertVersionMutex.Unlock()
	fake.InsertVersionStub = nil
	if fake.insertVersionReturnsOnCall == nil {
		fake.insertVersionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.insertVersionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Querier) LatestVersion(arg1 context.Context) (int64, error) {
	fake.latestVersionMutex.Lock()
	ret, specificReturn := fake.latestVersionReturnsOnCall[len(fake.latestVersionArgsForCall)]
	fake.latestVersionArgsForCall = append(fake.latestVersionArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.LatestVersionStub
	fakeReturns := fake.latestVersionReturns
	fake.recordInvocation("LatestVersion", []interface{}{arg1})
	fake.latestVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Querier) LatestVersionCallCount() int {
	fake.latestVersionMutex.RLock()
	defer fake.latestVersionMutex.RUnlock()
	return len(fake.latestVersionArgsForCall)
}

func (fake *Querier) LatestVersionCalls(stub func(context.Context) (int64, error)) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = stub
}

func (fake *Querier) LatestVersionArgsForCall(i int) context.Context {
	fake.latestVersionMutex.RLock()
	defer fake.latestVersionMutex.RUnlock()
	argsForCall := fake.latestVersionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Querier) LatestVersionReturns(result1 int64, result2 error) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = nil
	fake.latestVersionReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *Querier) LatestVersionReturnsOnCall(i int, result1 int64, result2 error) {
	fake.latestVersionMutex.Lock()
	defer fake.latestVersionMutex.Unlock()
	fake.LatestVersionStub = nil
	if fake.latestVersionReturnsOnCall == nil {
		fake.latestVersionReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.latestVersionReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *Querier) ListApplied(arg1 context.Context) ([]int64, error) {
	fake.listAppliedMutex.Lock()
	ret, specificReturn := fake.listAppliedReturnsOnCall[len(fake.listAppliedArgsForCall)]
	fake.listAppliedArgsForCall = append(fake.listAppliedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListAppliedStub
	fakeReturns := fake.listAppliedReturns
	fake.recordInvocation("ListApplied", []interface{}{arg1})
	fake.listAppliedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Querier) ListAppliedCallCount() int {
	fake.listAppliedMutex.RLock()
	defer fake.listAppliedMutex.RUnlock()
	return len(fake.listAppliedArgsForCall)
}

func (fake *Querier) ListAppliedCalls(stub func(context.Context) ([]int64, error)) {
	fake.listAppliedMutex.Lock()
	defer fake.listAppliedMutex.Unlock()
	fake.ListAppliedStub = stub
}

func (fake *Querier) ListAppliedArgsForCall(i int) context.Context {
	fake.listAppliedMutex.RLock()
	defer fake.listAppliedMutex.RUnlock()
	argsForCall := fake.listAppliedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Querier) ListAppliedReturns(result1 []int64, result2 error) {
	fake.listAppliedMutex.Lock()
	defer fake.listAppliedMutex.Unlock()
	fake.ListAppliedStub = nil
	fake.listAppliedReturns = struct {
		result1 []int64
		result2 error
	}{result1, result2}
}

func (fake *Querier) ListAppliedReturnsOnCall(i int, result1 []int64, result2 error) {
	fake.listAppliedMutex.Lock()
	defer fake.listAppliedMutex.Unlock()
	fake.ListAppliedStub = nil
	if fake.listAppliedReturnsOnCall == nil {
		fake.listAppliedReturnsOnCall = make(map[int]struct {
			result1 []int64
			result2 error
		})
	}
	fake.listAppliedReturnsOnCall[i] = struct {
		result1 []int64
		result2 error
	}{result1, result2}
}

func (fake *Querier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Querier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
