// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package libsql

import (
	"time"
)

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    time.Time
}
