// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"
)

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}
