// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package mysql

import (
	"context"
)

const deleteVersion = `-- name: DeleteVersion :exec
DELETE FROM goose_db_version WHERE version_id = ?
`

func (q *Queries) DeleteVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVersion, versionID)
	return err
}

const ensureTable = `-- name: EnsureTable :exec
CREATE TABLE IF NOT EXISTS goose_db_version (
    id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    version_id BIGINT NOT NULL,
    is_applied BOOLEAN NOT NULL,
    tstamp     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) EnsureTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureTable)
	return err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO goose_db_version (version_id, is_applied, tstamp)
VALUES (?, 1, NOW())
`

func (q *Queries) InsertVersion(ctx context.Context, versionID int64) error {
	_, err := q.db.ExecContext(ctx, insertVersion, versionID)
	return err
}

const latestVersion = `-- name: LatestVersion :one
SELECT CAST(COALESCE(MAX(version_id), 0) AS SIGNED) AS version_id
FROM goose_db_version
WHERE is_applied = 1
`

func (q *Queries) LatestVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestVersion)
	var version_id int64
	err := row.Scan(&version_id)
	return version_id, err
}

const listApplied = `-- name: ListApplied :many
SELECT DISTINCT version_id
FROM goose_db_version
WHERE is_applied = 1
ORDER BY version_id
`

func (q *Queries) ListApplied(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listApplied)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var version_id int64
		if err := rows.Scan(&version_id); err != nil {
			return nil, err
		}
		items = append(items, version_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
